#!/usr/bin/env ruby

# frozen_string_literal: true

require 'optparse'
require "full_time"

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: full_time [options] input template"
  opts.separator ""
  opts.separator "Options:"

  opts.on('-t', '--type TARGET', %i(html linkedin), "Export type: html, linkedin")
  opts.on('-v', '--version', "Version") do
    puts FullTime::VERSION
    exit
  end
  opts.on('-h', '--help', "Help") do
    puts opts
    exit
  end
end.parse!(into: options)

# Read DSL
require ARGV[0]

FullTime.export!(options[:type], ARGV[1])
